### ISSUE TITLE
Create a social preview

### ISSUE THREAD

**Issue by shaardie** [emissions-api/sentinel5algorithms#1]
We need a social preview picture.

**Comment by lkiesow** [comment]
a random sketch:

![__________31b285cb-5d2d-4943-9696-64ae15d8619f](https://user-images.githubusercontent.com/1008395/67584479-0aab0280-f74e-11e9-95e1-fd508356bb1a.jpeg)

…maybe something like this with the earth as background?

**Comment by lkiesow** [comment]
@tibroc fixed this by adding

![](https://repository-images.githubusercontent.com/217538083/f10fb800-f759-11e9-8970-80bca52b5f92)
