### ISSUE TITLE
Invalid Mask For Sulfur Dioxide

### ISSUE THREAD

**Issue by lkiesow** [emissions-api/sentinel5algorithms#23]
*—This is a sub-task of #22—*

Testing with sulfur dioxide instead of carbon monoxide, the import should be nearly identical.

We import different data:

```diff
diff --git a/s5a/__init__.py b/s5a/__init__.py
index 3ea7ac3..7832389 100644
--- a/s5a/__init__.py
+++ b/s5a/__init__.py
@@ -28,7 +28,7 @@ def load_ncfile(ncfile):
     # read in data
     with netCDF4.Dataset(ncfile, 'r') as f:
         variables = f.groups['PRODUCT'].variables
-        data = variables['carbonmonoxide_total_column'][:][0]
+        data = variables['sulfurdioxide_total_vertical_column'][:][0]
         longitude = variables['longitude'][:][0]
         latitude = variables['latitude'][:][0]
         quality = variables['qa_value'][:][0]
```

And then try importing [`S5P_OFFL_L2__SO2____20181231T235559_20190101T013729_06308_01_010105_20190107T091158.nc`](https://data.lkiesow.io/emissions-api/S5P_OFFL_L2__SO2____20181231T235559_20190101T013729_06308_01_010105_20190107T091158.nc):

```python
>>> import s5a
>>> s5a.load_ncfile('S5P_OFFL_L2__SO2____20181231T235559_20190101T013729_06308_01_010105_20190107T091158.nc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lars/dev/emissions-api/sentinel5algorithms/s5a/__init__.py", line 50, in load_ncfile
    deltatime_arr = deltatime_arr[mask]  # filter for missing data
  File "/home/lars/dev/emissions-api/sentinel5algorithms/venv/lib64/python3.7/site-packages/numpy/ma/core.py", line 3172, in __getitem__
    dout = self.data[indx]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 202500 but corresponding boolean dimension is 450
```

The line is question is

https://github.com/emissions-api/sentinel5algorithms/blob/fc44296c4654f86b2467e236661c478e1487788e/s5a/__init__.py#L50

…which should work just fine unless we are maybe using the mask incorrectly?

**Comment by tibroc** [comment]
This is kind of a weird problem, but easily fixable. The deltatime array for some products has one dimension, i.e. one timestamp for each scan line. For other products, however, the array has the same dimensionality as the data, i.e. a 2d-array with the timestamps for each scan line repeated for every pixel in that line. That is the reason that the dimensions don't match when applying the mask and you get the error you mentioned.

For reference, the two-dimensional products are:
* ozone ('L2__O3_____')
* formaldehyde ('L2__HCHO___')
* sulfur dioxide ('L2__SO2____')

I provide a simple fix in #24.
